nodeAgent:
  config:
    maxLearningPeriod: 5m
    learningPeriod: 2m
    updatePeriod: 1m
    #ruleCooldown:
    #  ruleCooldownDuration: 0.01h
    #  ruleCooldownAfterCount: 10
    #  ruleCooldownOnProfileFailure: true
    #  ruleCooldownMaxSize: 20000
capabilities:
  runtimeDetection: enable
  networkEventsStreaming: disable
  #nodeScan: disable
  #vulnerabilityScan: disable
  #relevancy: disable
  #seccompGenerator: enable
alertCRD:
  installDefault: true
  scopeClustered: true
  #scopeNamespaced: false
#persistence:
#  size:
#    backingStorage: 1Gi
clusterName: bobexample
ksNamespace: honey
excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public,honey,storm,lightening,cert-manager,openebs,kube-flannel,ingress-nginx,olm,pl,px-operator"